schema_version: 1

context:
  name: celery-types
  version: 0.22.0
  python_min: "3.9"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 0ecad2fa5a6eded0a1f919e5e1e381cc2ff0635fe4b21db53b4661b6876d5b30

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }}
    - typing_extensions >=4.9.0

tests:
  - package_contents:
      site_packages: 
        - amqp-stubs/__init__.pyi
        - billiard-stubs/__init__.pyi
        - celery-stubs/__init__.pyi
        - django_celery_results-stubs/__init__.pyi
        - ephem-stubs/__init__.pyi
        - kombu-stubs/__init__.pyi
        - vine-stubs/__init__.pyi

about:
  summary: Type stubs for Celery and its related packages
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/sbdchd/celery-types

extra:
  recipe-maintainers:
    - StevenSchaererQC
    - janjagusch
